[tool.black]
line-length = 100
target-version = ['py38']

[tool.isort]
# https://github.com/PyCQA/isort/wiki/isort-Settings
profile = "black"

# will group `import x` and `from x import` of the same module.
force_sort_within_sections = true

combine_as_imports = true

[tool.pylint.'MESSAGES CONTROL']
extension-pkg-whitelist = "pydantic"
